version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.4.1
    command: --mnemonic="text fall reveal replace bonus combine swap goat air bonus submit repair"
  tests:
    build: .
    environment:
      - GANACHE_TARGET=http://ganache:8545
      - GANACHE_HOST=ganache
      - GANACHE_PORT=8545
    depends_on:
      - ganache
    command: wait-for-ganache run
